version: '2'
services:
  node :
    build: .
    image: node:18-alpine
    ports:
      - 3000:3000
      - 9005:9005
      - 5000:5000
    volumes:
      - .:/app
    command: node /app/local.js