<<<<<<< HEAD
version: '3'
services:
  ftp:
    image: stilliard/pure-ftpd:hardened
=======
version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
>>>>>>> f04bffe9cad426a854a1429d7eb56d3187beb0c7
    ports:
      - 21:21
      - 30000-30009:30000-30009
    volumes:
<<<<<<< HEAD
      - "./data:/home/ftp"
      - "./passwd:/etc/pure-ftpd/passwd"
=======
      - ./data:/home/ftp
      - ./passwd:/etc/pure-ftpd/passwd
>>>>>>> f04bffe9cad426a854a1429d7eb56d3187beb0c7
    environment:
      - FTP_USER_NAME=ftp
      - FTP_USER_PASS=1234
      - FTP_USER_HOME=/home/ftp
<<<<<<< HEAD
    command: /run.sh  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -X -x   -p 30000:30009 -c 5 -C 5
=======
    command: /run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -X -x   -p 30000:30009 -c 5 -C 5
>>>>>>> f04bffe9cad426a854a1429d7eb56d3187beb0c7
